name: env-1
on:
  workflow_dispatch:
jobs:
  Environment:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo Hello world $FIRST_NAME $middle_name $Last_Name!
        env:
          FIRSTNAME: ${{ secrets.FIRSTNAME }}
          middle_name: ${{ secrets.middle_name }}
          Last_Name: ${{ secrets.Last_Name }}
          
