name: workflow-1
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      App1:
        description: 'App1' 
        default: 'App1'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  App1:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App1
      if: github.event.inputs.App1 == 'App1'
      run: echo "Hello ${{ github.event.inputs.App1 }}"
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '120s'
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: my-event
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: your-event
