name: workflow-2
on:
  repository_dispatch:
    types: [my-event]
    # Inputs the workflow accepts.
    inputs:
      App2:
        description: 'App2' 
        default: 'App2'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  App2:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App2
      if: github.event.inputs.App2 == 'App2'
      run: echo "Hello ${{ github.event.inputs.App2 }}"
