name: workflow-3
on:
  workflow_run:
    workflows: [workflow-1]
    types:
      - completed
    inputs:
      App2:
        description: 'App3' 
        default: 'App3'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  App2:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy App3
      if: github.event.inputs.App3 == 'App3'
      run: echo "Hello ${{ github.event.inputs.App3 }}"
